AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/DoubleNegation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 60

Metrics/PerceivedComplexity:
  Max: 15

Metrics/AbcSize:
  Max: 51

Metrics/CyclomaticComplexity:
  Max: 12

Lint/EmptyBlock:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames: e

Metrics/ParameterLists:
  Max: 6

Layout/LineLength:
  Max: 160
